//------------------------------------------------------------------------------
// <auto-generated>
//    此代码是根据模板生成的。
//
//    手动更改此文件可能会导致应用程序中发生异常行为。
//    如果重新生成代码，则将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace GGN.Center.Dal
{
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using GGN.Center.Entities;
    
    public partial class GGNCenterEntities : DbContext
    {
        public GGNCenterEntities()
            : base("name=GGNCenterEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public DbSet<Auth_DataObject> Auth_DataObject { get; set; }
        public DbSet<Auth_DataRole> Auth_DataRole { get; set; }
        public DbSet<Auth_DataRoleConfig> Auth_DataRoleConfig { get; set; }
        public DbSet<Auth_DataRoleDirectory> Auth_DataRoleDirectory { get; set; }
        public DbSet<Auth_FeatureRole> Auth_FeatureRole { get; set; }
        public DbSet<Auth_FeatureRoleConfig> Auth_FeatureRoleConfig { get; set; }
        public DbSet<Auth_FeatureRoleDirectory> Auth_FeatureRoleDirectory { get; set; }
        public DbSet<Auth_PositionDataRole> Auth_PositionDataRole { get; set; }
        public DbSet<Auth_PositionFeatureRole> Auth_PositionFeatureRole { get; set; }
        public DbSet<Auth_PositionSpecialMenuConfig> Auth_PositionSpecialMenuConfig { get; set; }
        public DbSet<Auth_UserDataRole> Auth_UserDataRole { get; set; }
        public DbSet<Auth_UserFeatureRole> Auth_UserFeatureRole { get; set; }
        public DbSet<Org_Group> Org_Group { get; set; }
        public DbSet<Org_Organization> Org_Organization { get; set; }
        public DbSet<Org_OrganizationCategory> Org_OrganizationCategory { get; set; }
        public DbSet<Org_Position> Org_Position { get; set; }
        public DbSet<Org_PositionCategory> Org_PositionCategory { get; set; }
        public DbSet<Org_PositionDefine> Org_PositionDefine { get; set; }
        public DbSet<Org_User> Org_User { get; set; }
        public DbSet<Org_UserPosition> Org_UserPosition { get; set; }
        public DbSet<Schedule_Log> Schedule_Log { get; set; }
        public DbSet<Schedule_Task> Schedule_Task { get; set; }
        public DbSet<Schedule_Type> Schedule_Type { get; set; }
        public DbSet<Sys_Application> Sys_Application { get; set; }
        public DbSet<Sys_ApplicationModule> Sys_ApplicationModule { get; set; }
        public DbSet<Sys_Feature> Sys_Feature { get; set; }
        public DbSet<Sys_Menu> Sys_Menu { get; set; }
        public DbSet<Sys_OpenInterface> Sys_OpenInterface { get; set; }
        public DbSet<Sys_OpenInterfaceType> Sys_OpenInterfaceType { get; set; }
        public DbSet<Sys_Region> Sys_Region { get; set; }
        public DbSet<Sys_StaticData> Sys_StaticData { get; set; }
        public DbSet<Sys_UserLoginHistory> Sys_UserLoginHistory { get; set; }
        public DbSet<Sys_UserLoginState> Sys_UserLoginState { get; set; }
        public DbSet<Sys_UserShortCutMenu> Sys_UserShortCutMenu { get; set; }
        public DbSet<View_Company> View_Company { get; set; }
        public DbSet<View_DataRolePosition> View_DataRolePosition { get; set; }
        public DbSet<View_FeaturePosition> View_FeaturePosition { get; set; }
        public DbSet<View_MenuSys> View_MenuSys { get; set; }
        public DbSet<View_UserOrgInfo> View_UserOrgInfo { get; set; }
    }
}
